### ISSUE TITLE
blah

### ISSUE THREAD

**Issue by auremoser** [auremoser/web-coding#1]
wow this sucks [link]()

**Comment by sayrequevedo** [comment]
Hey aurelia,

Sorry I didn't make it to class today. I've been sick all week. Meant to send something to you earlier but just woke up from a long nap. Anyways, I think I misunderstood using github. I can send you what I published yesterday, none of the formatting worked so I know I messed up somewhere. Thanks and see you next week!

Sayre

**Comment by auremoser** [comment]
Hey Sayre, 
Thanks for letting me know. Get well soon. Can you re-send your assignment? I'm not sure I received it?
